/// <summary>
/// This was generated by the EF Core command-line tools, using the following command:
/// `dotnet ef dbcontext scaffold "Data Source=<databases>\northwind_small.sqlite" Microsoft.EntityFrameworkCore.Sqlite -c Northwind -n MyLearning.Data.Sqlite  -o My_Learing\Data\Sqlite\Northwind`
/// </sumary>
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using MyLearning.Data.Sqlite.Northwind;

namespace MyLearning.Data.Sqlite;

public partial class NorthwindContext : DbContext
{
    private readonly string connectionString;

    public NorthwindContext(IConfiguration configuration)
    {
        connectionString = configuration.GetSqliteConnection() ?? throw new InvalidOperationException("Connection string not found.");
    }

    public NorthwindContext(DbContextOptions<NorthwindContext> options, IConfiguration configuration)
        : base(options)
    {
        connectionString = configuration.GetSqliteConnection() ?? throw new InvalidOperationException("Connection string not found.");
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<CustomerCustomerDemo> CustomerCustomerDemos { get; set; }

    public virtual DbSet<CustomerDemographic> CustomerDemographics { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeTerritory> EmployeeTerritories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductDetail> ProductDetails { get; set; }

    public virtual DbSet<Region> Regions { get; set; }

    public virtual DbSet<Shipper> Shippers { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    public virtual DbSet<Territory> Territories { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseSqlite(connectionString);

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.ToTable("Category");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CategoryName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Description).HasColumnType(SqliteContextHelper.DefaultTextDbType);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.ToTable("Customer");

            entity.Property(e => e.Id).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Address).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.City).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.CompanyName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ContactName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ContactTitle).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Country).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Fax).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Phone).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.PostalCode).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Region).HasColumnType(SqliteContextHelper.DefaultTextDbType);
        });

        modelBuilder.Entity<CustomerCustomerDemo>(entity =>
        {
            entity.ToTable("CustomerCustomerDemo");

            entity.Property(e => e.Id).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.CustomerTypeId).HasColumnType(SqliteContextHelper.DefaultTextDbType);
        });

        modelBuilder.Entity<CustomerDemographic>(entity =>
        {
            entity.ToTable("CustomerDemographic");

            entity.Property(e => e.Id).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.CustomerDesc).HasColumnType(SqliteContextHelper.DefaultTextDbType);
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.ToTable("Employee");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Address).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.BirthDate).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.City).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Country).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Extension).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.FirstName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.HireDate).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.HomePhone).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.LastName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Notes).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.PhotoPath).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.PostalCode).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Region).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Title).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.TitleOfCourtesy).HasColumnType(SqliteContextHelper.DefaultTextDbType);
        });

        modelBuilder.Entity<EmployeeTerritory>(entity =>
        {
            entity.ToTable("EmployeeTerritory");

            entity.Property(e => e.Id).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.TerritoryId).HasColumnType(SqliteContextHelper.DefaultTextDbType);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.ToTable("Order");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CustomerId).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Freight).HasColumnType(SqliteContextHelper.DecimalDbType);
            entity.Property(e => e.OrderDate).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.RequiredDate).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ShipAddress).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ShipCity).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ShipCountry).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ShipName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ShipPostalCode).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ShipRegion).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ShippedDate).HasColumnType(SqliteContextHelper.DefaultTextDbType);
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.ToTable("OrderDetail");

            entity.Property(e => e.Id).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Discount).HasColumnType("DOUBLE");
            entity.Property(e => e.UnitPrice).HasColumnType(SqliteContextHelper.DecimalDbType);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable("Product");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.ProductName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.QuantityPerUnit).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.UnitPrice).HasColumnType(SqliteContextHelper.DecimalDbType);
        });

        modelBuilder.Entity<ProductDetail>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("ProductDetails_V");

            entity.Property(e => e.CategoryDescription).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.CategoryName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ProductName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.QuantityPerUnit).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.SupplierName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.SupplierRegion).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.UnitPrice).HasColumnType(SqliteContextHelper.DecimalDbType);
        });

        modelBuilder.Entity<Region>(entity =>
        {
            entity.ToTable("Region");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.RegionDescription).HasColumnType(SqliteContextHelper.DefaultTextDbType);
        });

        modelBuilder.Entity<Shipper>(entity =>
        {
            entity.ToTable("Shipper");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CompanyName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Phone).HasColumnType(SqliteContextHelper.DefaultTextDbType);
        });

        modelBuilder.Entity<Supplier>(entity =>
        {
            entity.ToTable("Supplier");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Address).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.City).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.CompanyName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ContactName).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.ContactTitle).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Country).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Fax).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.HomePage).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Phone).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.PostalCode).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.Region).HasColumnType(SqliteContextHelper.DefaultTextDbType);
        });

        modelBuilder.Entity<Territory>(entity =>
        {
            entity.ToTable("Territory");

            entity.Property(e => e.Id).HasColumnType(SqliteContextHelper.DefaultTextDbType);
            entity.Property(e => e.TerritoryDescription).HasColumnType(SqliteContextHelper.DefaultTextDbType);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
